#!/bin/sh /etc/rc.common
# Copyright (C) mosdns

START=99
NAME=mosdns
USE_PROCD=1

start_mosdns() {
	procd_open_instance
	procd_set_param limits nofile="65535 65535"
	procd_set_param respawn
	procd_set_param command /usr/bin/mosdns start -c /etc/mosdns/config.yaml -d /etc/mosdns
	procd_close_instance
}

start_service() {
	echo "start mosdns success"
	start_mosdns
}

stop_service() {
	echo "stop mosdns success"
}