#!/bin/sh /etc/rc.common
#
# Copyright (C) 2018-2020 Ruilin Peng (Nick) <pymumu@gmail.com>.
#
# smartdns is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# smartdns is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

START=99
NAME=smartdns
USE_PROCD=1

start_smartdns() {
	procd_open_instance
	procd_set_param limits nofile="65535 65535"
	procd_set_param respawn
	procd_set_param command /usr/sbin/smartdns -f -c /etc/smartdns/smartdns.conf
	procd_close_instance
}

start_service() {
	echo "start smartdns success"
	start_smartdns
}

stop_service() {
	echo "stop smartdns success"
}
